name: tides-stack

services:
  volume-init:
    image: busybox:latest
    command: >
      sh -c "
        echo 'Checking volumes' &&
        mkdir -pv /spectra_volume/test_data &&
        mkdir -pv /static/plots &&
        echo 'Copying test data, if availible' &&
        cp -ru /test_data_src/* /spectra_volume/test_data/ 2>/dev/null || true &&
        echo 'Directories Ready'
      "
    volumes:
      - snid_api_runs_1:/snid_api_runs
      - ngsf_api_runs_1:/ngsf_api_runs
      - media_volume_1:/media
      - spectra_volume:/spectra_volume
      - deliveries_volume:/deliveries
      - static_volume_1:/static
      - ../test_data/sims:/test_data_src:ro #only for testing
    healthcheck:
      test: ["CMD-SHELL", "[ -d /static_volume/plots ] && [ -d /spectra_volume/test_data ]"]
      interval: 10s
      retries: 3
      start_period: 5s
    restart: "no"

include:
  - ./submodules/shared_services/docker-compose.yml
  - ./submodules/tides_pipe/docker-compose.yaml
  - ./submodules/tidestom/docker-compose.yml

volumes:
  snid_api_runs_1:
    #external: true
  ngsf_api_runs_1:
    #external: true
  media_volume_1:
    #external: true
  spectra_volume:
    #external: true
  deliveries_volume:
    #external: true
  static_volume_1:
    #external: true

networks:
  backend:
    name: tides-stack_backend
    driver: bridge
