name: tides-stack
include:
  - ./submodules/shared_services/docker-compose.yml
  - ./submodules/tides_pipe/docker-compose.yaml
  - ./submodules/tidestom/docker-compose.yml

volumes:
  snid_api_runs_1:
    #external: true
  ngsf_api_runs_1:
    #external: true
  media_volume_1:
    #external: true
  spectra_volume:
    #external: true
  deliveries_volume:
    #external: true
  static_volume_1:
    #external: true

networks:
  backend:
    name: tides-stack_backend
    driver: bridge
