name: Update Submodules

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Update submodules (main)
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git submodule update --remote --merge
          git add submodules
          git commit -m "Update submodules (main)" || echo "No changes"
          git push origin main

      - name: Update submodules (dev)
        run: |
          git fetch origin dev
          git checkout dev
          git submodule update --remote --merge
          git add submodules
          git commit -m "Update submodules (dev)" || echo "No changes"
          git push origin dev
