name: Update Submodules

permissions:
  contents: write
  pull-requests: write

on:
  schedule:
    - cron: '0 0/3 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        branch: [main, dev]

    steps:
      # Checkout repository and submodules
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # Configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      # Switch to target branch
      - name: Checkout branch
        run: git checkout ${{ matrix.branch }}

      # Update submodules
      - name: Update submodules
        id: submodules
        run: |
          CHANGED=0
          git submodule foreach --quiet '
            echo "Updating $name..."
            git fetch origin
            git merge --ff-only origin/$(git rev-parse --abbrev-ref HEAD) || true
            if ! git diff --quiet; then
              git add .
              CHANGED=1
            fi
          '
          echo "changed=$CHANGED" >> $GITHUB_OUTPUT

      # Create PR if changes detected
      - name: Create Pull Request
        if: steps.submodules.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: auto/submodule-update-${{ matrix.branch }}
          base: ${{ matrix.branch }}
          title: Automated submodule update (${{ matrix.branch }})
          body: This PR updates all submodules automatically.
          commit-message: Automated update of all submodules (${{ matrix.branch }})
          labels: automation
          draft: false

      # Auto-merge PR if created
      - name: Auto-merge PR
        if: steps.submodules.outputs.changed == '1'
        run: |
          gh pr merge auto/submodule-update-${{ matrix.branch }} --squash --auto --delete-branch || echo "No PR to merge"

      # Cleanup old auto-update branches
      - name: Cleanup old branches
        run: |
          AUTO_BRANCH=auto/submodule-update-${{ matrix.branch }}
          if gh pr view $AUTO_BRANCH --json mergedAt -q '.mergedAt' | grep -qv null; then
            git push origin --delete $AUTO_BRANCH || echo "Branch $AUTO_BRANCH not found, skipping"
          fi
